use gatesim::*;

// generated by using gen_all_4bit_funcs from crate gateexamples0.
// Line format: number_of_values list_of_inputs circuit
// number_of_values - decimal value of combination of outputs for all input values.
//     start from lowest bit.
//     Example: 9 - 0b1001 - true for 0b0001 (1 value and bit) and 0b0011 (3 value and bit).
// list_of_inputs - int Rust format list of inputs.
//     index - final input bit, value - original input bit.
// circuit - circuit in printable form.
const PERFECT_4INPUT_CIRCUITS: &str = include_str!("all_4bit_funcs.txt");

use crate::xor_table::*;
